Resources:
Ec2Instance:
 Type: 'AWS::EC2::Instance'
 Properties:
   SecurityGroups:
     - !Ref InstanceSecurityGroup
   KeyName: mod03Key
   ImageId: 'ami-09e67e426f25ce0d7' # check instance availability: https://cloud-images.ubuntu.com/locator/ec2/
InstanceSecurityGroup:
 Type: 'AWS::EC2::SecurityGroup'
 Properties:
   GroupDescription: Enable SSH access via port 22 and ICMP
   SecurityGroupIngress:
     - IpProtocol: tcp
       FromPort: '22'
       ToPort: '22'
       CidrIp: 0.0.0.0/0
     - IpProtocol: icmp
       FromPort: -1
       ToPort: -1
       CidrIp: 0.0.0.0/0